import Head from 'next/head'
import NavSidebar from '../components/NavSidebar'
import Feed from '../components/Feed'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black min-h-screen flex max-w-[1500px] mx-auto'>
        <NavSidebar />
        <Feed />
        {/* widgets */}

        {/* Modal */}
      </main>
    </div>
  )
}
